# Use root/example as user/password credentials
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPass
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
